# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fibs():
  previous, current = 0, 1
  while True:
    previous, current = current, previous + current
    yield current

def problem2(bound):
  sum = 0
  for n in fibs():
    if n >= bound:
      break
    if n % 2 == 0:
      sum += n
  return sum

print problem2(4000000)